name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    #timeout-minutes: 20000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        timeout-minutes: 20000
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
